#!/usr/bin/env python

# This script is autogenerated by Autocmake
# Copyright (c) 2015 by Radovan Bast and Jonas Juselius
# See https://github.com/scisoft/autocmake/blob/master/LICENSE

import os
import sys

sys.path.append('cmake/lib')
from config import configure
from docopt import docopt


options = """
Usage:
  ./setup.py [options] [<builddir>]
  ./setup.py (-h | --help)

Options:
  --cc=<CC>                           C compiler [default: gcc].
  --extra-cc-flags=<EXTRA_CFLAGS>     Extra C compiler flags [default: ''].
  --cxx=<CXX>                         C++ compiler [default: g++].
  --extra-cxx-flags=<EXTRA_CXXFLAGS>  Extra C++ compiler flags [default: ''].
  --coverage                          Enable code coverage [default: False].
  --type=<TYPE>                       Set the CMake build type (debug, release, or relwithdeb) [default: release].
  --show                              Show CMake command and exit.
  <builddir>                          Build directory.
  -h --help                           Show this screen.
"""


def gen_cmake_command(options, arguments):
    """
    Generate CMake command based on options and arguments.
    """
    command = []
    command.append('CC=%s' % arguments['--cc'])
    command.append('CXX=%s' % arguments['--cxx'])
    command.append('cmake')
    command.append('-DEXTRA_CFLAGS="%s"' % arguments['--extra-cc-flags'])
    command.append('-DEXTRA_CXXFLAGS="%s"' % arguments['--extra-cxx-flags'])
    command.append('-DENABLE_CODE_COVERAGE=%s' % arguments['--coverage'])
    command.append('-DCMAKE_BUILD_TYPE=%s' % arguments['--type'])

    return ' '.join(command)


arguments = docopt(options, argv=None)

root_directory = os.path.dirname(os.path.realpath(__file__))
build_path = arguments['<builddir>']
cmake_command = '%s %s' % (gen_cmake_command(options, arguments), root_directory)
configure(root_directory, build_path, cmake_command, arguments['--show'])
