include_directories(${PROJECT_SOURCE_DIR}/api)

file(MAKE_DIRECTORY ${PROJECT_BINARY_DIR}/include)

file(COPY ${PROJECT_SOURCE_DIR}/api/numgrid.h  DESTINATION ${PROJECT_BINARY_DIR}/include)
file(COPY ${PROJECT_SOURCE_DIR}/api/numgrid.py DESTINATION ${PROJECT_BINARY_DIR})
