name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build crate
      run: cargo build --verbose
    - name: Test crate
      run: cargo test --verbose
    - name: Package crate
      run: cargo package
    - name: Verify a dry-run publish
      run: cargo publish --dry-run
    - name: Build and test the Python interface
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        maturin develop
        pytest tests/test.py
        maturin build
